version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SIMLI_API_KEY: ${NEXT_PUBLIC_SIMLI_API_KEY}
        ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_SIMLI_API_KEY: ${NEXT_PUBLIC_SIMLI_API_KEY}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
    ports:
      - "3000:3000"
    restart: unless-stopped
